[workspace]
members = ["bindings", "cli"]

[workspace.dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false, features = [
  "abigen",
] }
eyre = "0.6.8"
tokio = { version = "1.21.1", features = ["macros"] }
