[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "hardhat/=lib/forge-std/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]
